// <auto-generated />
using System;
using Armali.Horizon.Segaris;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Armali.Horizon.Segaris.Migrations
{
    [DbContext(typeof(SegarisDbContext))]
    [Migration("20260209182348_ClothesEntities")]
    partial class ClothesEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Other devices"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Decoration"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Commodities"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vehicles"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("AssetEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "gold",
                            Name = "Unavailable"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapexCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Food and Drinks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Social Expenses"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Medicines"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Assets"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Public Transport"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Housing"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("CapexEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapexStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Color = "red",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.ClothesCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClothesCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Short T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Long T-Shirt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Short Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Long Shirt"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Short Polo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Long Polo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Short Trouser"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Long Trouser"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jacket"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Coat"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Footwear"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.ClothesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("GarmentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WashTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("ClothesEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.ClothesStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClothesStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "red",
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.ClothesWashType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClothesWashTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White Wash"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Color Wash"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Special Wash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wash Alone"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FirebirdCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cat A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cat C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cat D"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cat E"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cat F"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAware")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("FirebirdEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FirebirdStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "red",
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            Color = "gray",
                            Name = "Blocked"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdSubEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FirebirdId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirebirdId");

                    b.ToTable("FirebirdSubEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvItemCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bath Amenities"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty Products"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cleaning Products"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Medicines"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Complements"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Raw Ingredients"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Food Condiments"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Meal Ready to Eat"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Other Consumibles"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VendorId");

                    b.ToTable("InvItemEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvItemStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Color = "red",
                            Name = "Deprecated"
                        },
                        new
                        {
                            Id = 3,
                            Color = "blue",
                            Name = "Replaced"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvVendorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("InvVendorEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvVendorStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvVendorStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "red",
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Platform"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Decoration"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Assets"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("MaintEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Color = "gold",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpexCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Facilities"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("OpexEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpexStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "gold",
                            Name = "Paused"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexSubEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("OpexSubEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Local"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regional"
                        },
                        new
                        {
                            Id = 3,
                            Name = "National"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Schengen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Non-Schengen"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelCostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelCostCenters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Armali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Common Fund"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AMI3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Other CC"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pax")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("StatusId");

                    b.ToTable("TravelEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "gold",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelSubEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TravelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TravelId");

                    b.ToTable("TravelSubEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelSubEntityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TravelSubEntityCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hotels"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Other Lodging"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Airplane"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Train"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Car Rental"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Metro"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Taxi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Other Transport"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Food and Drinks"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Souvenirs"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Visa or eTA"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Other Expenses"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.AssetStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.CapexCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.CapexStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.ClothesEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.ClothesCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.ClothesWashType", "WashType")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.ClothesStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("WashType");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.FirebirdCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.FirebirdStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.FirebirdSubEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.FirebirdEntity", "Contract")
                        .WithMany()
                        .HasForeignKey("FirebirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvItemEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.InvItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.InvItemStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.InvVendorEntity", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.InvVendorEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.InvVendorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.MaintCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.MaintStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.OpexCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.OpexStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.OpexSubEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.OpexEntity", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.TravelCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.TravelCostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.TravelStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CostCenter");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.TravelSubEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.TravelSubEntityCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.TravelEntity", "Travel")
                        .WithMany()
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Travel");
                });
#pragma warning restore 612, 618
        }
    }
}
