// <auto-generated />
using System;
using Armali.Horizon.Segaris;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Armali.Horizon.Segaris.Migrations
{
    [DbContext(typeof(SegarisDbContext))]
    [Migration("20260206114114_MaintFiles")]
    partial class MaintFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Other devices"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Decoration"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Commodities"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vehicles"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("AssetEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AssetStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "gold",
                            Name = "Unavailable"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapexCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Government"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Investment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Food and Drinks"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Social Expenses"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Medicines"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Assets"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Public Transport"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Housing"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("CapexEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapexStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Planning"
                        },
                        new
                        {
                            Id = 2,
                            Color = "green",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Color = "red",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Platform"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Appliances"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Decoration"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Assets"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StatusId");

                    b.ToTable("MaintEntities");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Name = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Color = "gold",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Color = "green",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.AssetEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.AssetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.AssetStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.CapexEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.CapexCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.CapexStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Armali.Horizon.Segaris.Model.MaintEntity", b =>
                {
                    b.HasOne("Armali.Horizon.Segaris.Model.MaintCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Armali.Horizon.Segaris.Model.MaintStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
